### ISSUE TITLE
JDBCRun cannot write SPL blobs to DB2 tables as BLOBs

### ISSUE THREAD

**Issue by brandtol** [IBMStreams/streamsx.jdbc#82]
When writing an SPL blob, the following SQL error is logged

Invalid data conversion: Parameter instance 746573742D746573742D74657374 is invalid for the requested conversion. ERRORCODE=-4461, SQLSTATE=42815

The problem is that the jdbs driver is not converting spl blobs to java.sql.Blob when using the setObject() method on the prepared statement. We need ti use the setBlob() method instead.

**Tasks**
- [x] add correction for writing blobs
- [x] enhance testcase for writing different datatypes
- [x] test behaviour when fetching blobs from DB2
- [x] test with other databases than DB2

**Comment by brandtol** [comment]
Added a correction on master branch.

**Comment by brandtol** [comment]
Added another correction for reading blob columns from DB2 via SELECT statement

**Comment by anouri** [comment]
A new test case has been created to check all data types.

**Comment by anouri** [comment]
A new SPL application created to test all data types in a ORACLE database.
The application 
- creates a table with 14 columns
- writes (INSERT) data in all types into ORACLE table
- reads (SELECT)  data from table
- drop the test table

**Comment by anouri** [comment]
Correction delivered in:
https://github.com/IBMStreams/streamsx.jdbc/releases/tag/v1.4.4
